all:
  vars:
    pi_ip: "114.23.105.165"
    vault_addr: "https://192.168.198.133:8200"
    elk_host: "192.168.198.134"
    backup_retention_days: 7
    prometheus_storage: "/mnt/usb/prometheus"
    lab_network: "192.168.198.0/24"
    k3s_version: "v1.28.5+k3s1"
    argocd_version: "v2.9.3"

raspberry_pi:
  hosts:
    edge-pi:
      ansible_host: 114.23.105.165
      ansible_user: ubuntu
      k3s_node_role: server
      usb_device: "/dev/sda1"
      usb_mount: "/mnt/usb"